### ISSUE TITLE
Exists function is crashing. 

### ISSUE THREAD

**Issue by TimotheeJeannin** [fabric/patchwork#18]
Here is the error I have when I try to use the `exists` function:

    Traceback (most recent call last):
      File "env/bin/fab", line 9, in <module>
        load_entry_point('fabric==2.0.0', 'console_scripts', 'fab')()
      File "/home/tim/Workspace/wintest/env/lib/python3.5/site-packages/invoke/program.py", line 332, in run
        self.execute()
      File "/home/tim/Workspace/wintest/env/lib/python3.5/site-packages/invoke/program.py", line 480, in execute
        executor.execute(*self.tasks)
      File "/home/tim/Workspace/wintest/env/lib/python3.5/site-packages/invoke/executor.py", line 133, in execute
        result = call.task(*args, **call.kwargs)
      File "/home/tim/Workspace/wintest/env/lib/python3.5/site-packages/invoke/tasks.py", line 127, in __call__
        result = self.body(*args, **kwargs)
      File "/home/tim/Workspace/wintest/fabfile.py", line 58, in website_dependencies
        if not exists(context, remote_env_path):
      File "/home/tim/Workspace/wintest/env/lib/python3.5/site-packages/patchwork/util.py", line 113, in inner
        return f(*args, **kwargs)
      File "/home/tim/Workspace/wintest/env/lib/python3.5/site-packages/patchwork/files.py", line 31, in exists
        return runner(cmd, hide=True, warn=True).succeeded
    AttributeError: 'Result' object has no attribute 'succeeded'

It looks like the attribute `succeeded` have been replaced with `ok` in recent versions.

**Comment by TimotheeJeannin** [comment]
Just realized there is a pull request for this : https://github.com/fabric/patchwork/pull/17
