### ISSUE TITLE
cannot import name 'six' from 'invoke.vendor'

### ISSUE THREAD

**Issue by nmgeek** [fabric/patchwork#41]
>>> import patchwork._version
>>> patchwork._version.__version__
'1.0.1'
>>> import invoke
>>> invoke.__version__
'1.3.0'
>>> import patchwork.files
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/patchwork/files.py", line 7, in <module>
    from invoke.vendor import six
ImportError: cannot import name 'six' from 'invoke.vendor' (/usr/lib/python3/dist-packages/invoke/vendor/__init__.py)

**Comment by tasosalvas** [comment]
works for me on invoke 1.4.1

**Comment by nmgeek** [comment]
Indeed it does work.  

So the dependent package requirements are wrong in pathwork 1.0.1.  It should _not_ be satisfied with invoke version 1.3.0.  It requires a later version to avoid the crash I posted above.

```
$ pip3 install patchwork
...
Requirement already satisfied: invoke<2.0,>=1.3 in /usr/lib/python3/dist-packages (from fabric<3.0,>=2.0->patchwork) (1.3.0)

```

**Comment by tasosalvas** [comment]
Fair, yeah.
I think @bitprophet might be a bit overloaded at the moment but it's a pretty straightforward PR to fix.
